application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT:8086}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_EMAIL}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: ${SPRING_MAIL_EMAIL_SENDER}
    recipient:
      postfix-email: ${SPRING_MAIL_EMAIL_POSTFIX}

  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml

page:
  default-size: 30