application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml
