application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT:8086}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: 'jdbc:postgresql://localhost:5432/admin_service'
    username: 'root'
    password: 'root'

  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml
