application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT:8086}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    host: smtp.mail.ru
    port: 587
    username: mailto:myemail@example.com
    password: myemailpassword
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
    sender:
      email: mailto:sender@mail.ru
    recipient:
      postfix-email: "@mail.ru"

  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

page:
  default-size: 30