application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT:8086}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/admin_service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_EMAIL:Sokol66777@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:nqcbaekkmzfaoyhj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: ${SPRING_MAIL_EMAIL_SENDER:Sokol66777@gmail.com}
    recipient:
      postfix-email: ${SPRING_MAIL_EMAIL_POSTFIX:@gmail.com}

  liquibase:
    enabled: 'true'
    change-log: classpath:liquibase/changelog-master.yml
