application:
  name: admin-service

server:
  port: ${ADMIN_SERVICE_PORT:8086}

spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
