include:
  - project: 'rvaliev/devops'
    ref: main
    file:
      - 'templates/sonar-template.yml'

stages:
  - test

run-test:
  stage: test
  extends: .sonar-mvn-template-jdk17
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
