version: '3'

services:

  app-admin-service:
    image: ${AND_DOCKER_REGISTRY_NAME}/${PROJECT}-${APP}:${CI_COMMIT_BRANCH}
    container_name: ${APP}-${CI_COMMIT_BRANCH}
    restart: unless-stopped
    volumes:
      - ./:/var/www

  admin-webserver:
    image: nginx:1.23
    container_name: admin-service-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf


  admin-service-db:
    image: mysql:8.0
    container_name: admin-service-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: admin_service
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata_admin_service:/var/lib/mysql/


volumes:
  dbdata_admin_service:
    driver: local

