services:
    app:
        restart: unless-stopped

    webserver:
        image: nginx:1.23
        container_name: admin-service-webserver
        restart: unless-stopped

    db:
        image: mysql:8.0
        container_name: admin-service-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
