package ru.aston.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    /**
     * Employee primary key. Generated by incrementation strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "employee_id")
    private Long id;

    /**
     * UUID of employee. Used to connect to other services.
     * Must be unique and not null.
     */
    @Column(name = "employee_uuid", nullable = false, unique = true)
    private UUID uuid;

    /**
     * Surname of employee. Represented as a 30-character string.
     * Can not be null.
     */
    @Column(name = "surname", nullable = false)
    private String surname;

    /**
     * Name of employee. Represented as a 30-character string.
     * Can not be null.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Middle name of employee. Represented as a 30-character string.
     * Can not be null.
     */
    @Column(name = "middle_name", nullable = false)
    private String middleName;

    /**
     * Login is a part of credentials used to access a service.
     * Represented as a 30-character string.
     * Must be unique and not null.
     */
    @Column(name = "login", nullable = false, unique = true)
    private String login;

    /**
     * Password is a part of credentials used to access a service.
     * Represented as a 20-character string.
     * Can not be null.
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * Identification number of employees passport.
     * Can not be null.
     */
    @Column(name = "passport_ID", nullable = false)
    private Long passportId;

    /**
     * Employee passport issued date.
     * Can not be null.
     */
    @Column(name = "passport_date_issue", nullable = false)
    private LocalDate passportDateIssue;

    /**
     * Reference to employee role.
     *
     * @see Role
     */
    @ManyToOne
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    /**
     * Reference to employee status.
     *
     * @see Status
     */
    @ManyToOne
    @JoinColumn(name = "status_id", nullable = false)
    private Status status;

    /**
     * Time of creation. Represent as a timestamp.
     */
    @Column(name = "created_at")
    @CreationTimestamp
    private Instant createdAt;

    /**
     * Time of the last modification. Represent as a timestamp.
     */
    @Column(name = "modified_at")
    @UpdateTimestamp
    private Instant modifiedAt;
}
