package ru.aston.model;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GeneratePassword {

    /**
     * GeneratePassword primary key. Generated by incrementation strategy.
     */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The meaning of the password
     * Represented as a 20-character string.
     * Can not be null.
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * Password update time
     * Can not be null.
     */
    @Column(name = "modified_at", nullable = false)
    @UpdateTimestamp
    private LocalDateTime modifiedAt;
}
